/**
 * GermlineRx — Static (Browser-Only) Engine
 *
 * Runs entirely in the browser with no backend server.
 * - Tier 1 / Tier 3: loaded from bundled JSON knowledge bases
 * - Tier 0: direct browser fetch to ClinVar (NCBI) + gnomAD GraphQL
 * - Tier 2: direct browser fetch to ClinicalTrials.gov v2 API
 * - Enrichment: skipped in static mode (requires local datalake files)
 *
 * JSON knowledge bases are generated by running:
 *   python scripts/export_kb_to_json.py
 */

import type {
  NormalizeResponse,
  AnalyzeResponse,
  Tier0Result,
  Tier1Result,
  Tier2Result,
  Tier3Result,
  DrugEntry,
  SurveillanceEntry,
  TrialResult,
  PipelineEntry,
} from '../types'

import tier1Data from './tier1_kb.json'
import tier3Data from './tier3_kb.json'
import aliasData from './alias_table.json'

// ─── Normalizer ───────────────────────────────────────────────────────────────

const ALIASES: Record<string, { gene: string; hgvs: string; display: string; fc: string | null; note: string }> =
  (aliasData as { aliases: Record<string, { gene: string; hgvs: string; display: string; fc: string | null; note: string }> }).aliases || {}

const DISEASE_TO_GENE: Record<string, string> =
  (aliasData as { disease_to_gene: Record<string, string> }).disease_to_gene || {}

export function staticNormalize(disease: string, mutationText: string): NormalizeResponse {
  const raw = mutationText.trim()
  const key = raw.toLowerCase().trim()

  // Gene-only mode
  if (!raw) {
    const gene = extractGeneFromDisease(disease)
    if (gene) {
      return buildResult('', gene, 'unknown', `${gene} (gene-only)`, null, 'LOW',
        `Gene ${gene} identified; no specific variant provided — showing gene-level results`)
    }
    return buildResult('', 'UNKNOWN', 'unknown', '', null, 'LOW', 'No mutation or recognizable gene provided')
  }

  // Direct alias lookup
  if (ALIASES[key]) {
    const e = ALIASES[key]
    return buildResult(raw, e.gene, e.hgvs, e.display, e.fc, 'HIGH', e.note)
  }

  // Substring alias match
  for (const [aliasKey, e] of Object.entries(ALIASES)) {
    if (aliasKey.includes(key) || key.includes(aliasKey)) {
      return buildResult(raw, e.gene, e.hgvs, e.display, e.fc, 'HIGH', e.note)
    }
  }

  // HGVS c. notation
  const hgvsMatch = raw.match(/c\.[0-9A-Za-z_>+\-*?]+/)
  if (hgvsMatch) {
    const gene = extractGeneFromDisease(disease)
    return buildResult(raw, gene || 'UNKNOWN', hgvsMatch[0], hgvsMatch[0], null, 'MODERATE',
      `HGVS notation detected: ${hgvsMatch[0]}`)
  }

  // rsID
  const rsMatch = raw.match(/rs\d+/i)
  if (rsMatch) {
    const gene = extractGeneFromDisease(disease)
    return buildResult(raw, gene || 'UNKNOWN', rsMatch[0], rsMatch[0], null, 'MODERATE',
      'rsID detected — looking up in ClinVar')
  }

  // Protein notation p.XXXnnnYYY
  const protMatch = raw.match(/p\.[A-Za-z]{1,3}\d+[A-Za-z*]{1,3}|[A-Z][a-z]{2}\d+[A-Za-z*]/)
  if (protMatch) {
    const gene = extractGeneFromDisease(disease)
    const display = protMatch[0].replace(/^p\./, '')
    return buildResult(raw, gene || 'UNKNOWN', `p.${display}`, display, null, 'LOW',
      'Protein notation detected — HGVS lookup recommended')
  }

  // Gene-only fallback
  const gene = extractGeneFromDisease(disease)
  if (gene) {
    return buildResult(raw, gene, 'unknown', raw, null, 'LOW',
      `Gene ${gene} inferred from disease context; mutation not recognized`)
  }

  return buildResult(raw, 'UNKNOWN', 'unknown', raw, null, 'LOW',
    'Mutation format not recognized — please use HGVS notation or common name')
}

function extractGeneFromDisease(disease: string): string | null {
  // Check known gene symbols (2–10 uppercase letters) in the input
  const geneMatch = disease.match(/\b([A-Z][A-Z0-9]{1,9})\b/)
  if (geneMatch) return geneMatch[1]
  // Disease name → gene mapping
  const lower = disease.toLowerCase()
  for (const [d, g] of Object.entries(DISEASE_TO_GENE)) {
    if (lower.includes(d)) return g
  }
  return null
}

function buildResult(
  original: string, gene: string, hgvs: string, display: string,
  fc: string | null, confidence: 'HIGH' | 'MODERATE' | 'LOW', note: string
): NormalizeResponse {
  return { original_text: original, gene, hgvs, display_mutation: display, functional_class: fc, confidence, note }
}

// ─── Tier 1 matching ──────────────────────────────────────────────────────────

function matchTier1(gene: string, functionalClass: string | null): Tier1Result {
  const kb = tier1Data as Array<{
    gene: string
    match_functional_classes: string[] | null
    action_type: string
    drug_name?: string
    action?: string
    recommendation?: string
    fda_approved?: boolean
    approval_year?: string
    evidence_level: string
    line?: string
    caveat?: string
    source?: string
  }>

  const drugs: DrugEntry[] = []
  const surveillance: SurveillanceEntry[] = []

  for (const entry of kb) {
    if (entry.gene !== gene) continue
    const fcMatch =
      entry.match_functional_classes === null ||
      (functionalClass !== null && entry.match_functional_classes.includes(functionalClass))
    if (!fcMatch) continue

    if (entry.action_type === 'drug' && entry.drug_name) {
      drugs.push({
        drug_name: entry.drug_name,
        action: entry.action || '',
        fda_approved: entry.fda_approved ?? false,
        approval_year: entry.approval_year || null,
        evidence_level: entry.evidence_level,
        line: entry.line || null,
        caveat: entry.caveat || null,
        source: entry.source || null,
      })
    } else if ((entry.action_type === 'surveillance' || entry.action_type === 'surgery') && (entry.action || entry.recommendation)) {
      surveillance.push({
        recommendation: entry.action || entry.recommendation || '',
        action_type: entry.action_type,
        evidence_level: entry.evidence_level,
        source: entry.source || null,
      })
    }
  }

  return { drugs, surveillance }
}

// ─── Tier 3 matching ──────────────────────────────────────────────────────────

function matchTier3(gene: string): Tier3Result {
  const kb = tier3Data as PipelineEntry[]
  const pipeline = kb.filter(e => e.gene === gene)
  return { pipeline }
}

// ─── Tier 0: ClinVar + gnomAD (direct browser fetch) ─────────────────────────

async function fetchTier0(gene: string, hgvs: string): Promise<Tier0Result> {
  const fallback: Tier0Result = {
    classification: 'Unknown significance',
    confidence: 'LOW',
    review_stars: 0,
    review_status: 'No data',
    gnomad_af: null,
    gnomad_interpretation: 'No frequency data',
    clinvar_id: null,
    clingen_note: null,
  }

  if (hgvs === 'unknown' || !hgvs) return fallback

  try {
    // ClinVar search
    const searchQuery = encodeURIComponent(`${gene}[gene] AND "${hgvs}"[variant name]`)
    const searchUrl = `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=${searchQuery}&retmode=json&retmax=1`
    const searchRes = await fetch(searchUrl)
    const searchJson = await searchRes.json()
    const ids: string[] = searchJson?.esearchresult?.idlist || []

    if (ids.length === 0) return fallback

    const clinvarId = ids[0]
    const summaryUrl = `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=clinvar&id=${clinvarId}&retmode=json`
    const summaryRes = await fetch(summaryUrl)
    const summaryJson = await summaryRes.json()
    const result = summaryJson?.result?.[clinvarId]

    const classification = result?.clinical_significance?.description || 'Unknown significance'
    const reviewStatus = result?.clinical_significance?.review_status || 'no assertion'
    const stars = reviewStatusToStars(reviewStatus)

    // gnomAD query
    let af: number | null = null
    let afInterpretation = 'No frequency data'
    try {
      const gnomadQuery = `{ gene(gene_symbol: "${gene}", reference_genome: GRCh38) { variants(dataset: gnomad_r4) { variant_id exome { ac an af } } } }`
      const gnomadRes = await fetch('https://gnomad.broadinstitute.org/api', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: gnomadQuery }),
      })
      const gnomadJson = await gnomadRes.json()
      const variants = gnomadJson?.data?.gene?.variants || []
      if (variants.length > 0) {
        const totalAc = variants.reduce((s: number, v: { exome?: { ac: number } }) => s + (v.exome?.ac || 0), 0)
        const totalAn = variants.reduce((s: number, v: { exome?: { an: number } }) => s + (v.exome?.an || 0), 0)
        if (totalAn > 0) {
          af = totalAc / totalAn
          afInterpretation = af < 0.0001 ? 'Very rare (AF < 0.01%)' :
            af < 0.01 ? 'Rare (AF < 1%)' : 'Common variant'
        }
      }
    } catch { /* gnomAD unavailable */ }

    return {
      classification,
      confidence: stars >= 2 ? 'HIGH' : stars === 1 ? 'MODERATE' : 'LOW',
      review_stars: stars,
      review_status: reviewStatus,
      gnomad_af: af,
      gnomad_interpretation: afInterpretation,
      clinvar_id: clinvarId,
      clingen_note: null,
    }
  } catch {
    return fallback
  }
}

function reviewStatusToStars(status: string): number {
  if (status.includes('practice guideline')) return 4
  if (status.includes('reviewed by expert')) return 3
  if (status.includes('criteria provided, multiple')) return 2
  if (status.includes('criteria provided, single')) return 1
  return 0
}

// ─── Tier 2: ClinicalTrials.gov (direct browser fetch) ───────────────────────

async function fetchTier2(gene: string, disease: string, age: number | null): Promise<Tier2Result> {
  try {
    const query = encodeURIComponent(`${gene} ${disease}`)
    const url = `https://clinicaltrials.gov/api/v2/studies?query.term=${query}&filter.overallStatus=RECRUITING&pageSize=10&format=json`
    const res = await fetch(url)
    const json = await res.json()
    const studies = json?.studies || []

    const trials: TrialResult[] = studies
      .map((s: {
        protocolSection?: {
          identificationModule?: { nctId?: string; briefTitle?: string }
          statusModule?: { overallStatus?: string }
          designModule?: { phases?: string[] }
          conditionsModule?: { conditions?: string[] }
          armsInterventionsModule?: { interventions?: Array<{ name?: string }> }
          eligibilityModule?: { eligibilityCriteria?: string; minimumAge?: string; maximumAge?: string }
          contactsLocationsModule?: { centralContacts?: Array<{ name?: string; email?: string; phone?: string }> }
        }
      }) => {
        const p = s.protocolSection || {}
        const id = p.identificationModule || {}
        const elig = p.eligibilityModule || {}
        const contacts = p.contactsLocationsModule?.centralContacts || []
        const nctId = id.nctId || 'N/A'

        // Simple age eligibility check
        let eligOverall: TrialResult['eligibility_overall'] = 'CHECK_WITH_DOCTOR'
        if (age !== null) {
          const minAge = parseAgeYears(elig.minimumAge || '0 years')
          const maxAge = parseAgeYears(elig.maximumAge || '120 years')
          eligOverall = (age >= minAge && age <= maxAge) ? 'LIKELY_ELIGIBLE' : 'CHECK_WITH_DOCTOR'
        }

        return {
          nct_id: nctId,
          title: id.briefTitle || 'Untitled Trial',
          phase: (p.designModule?.phases || []).join(', ') || null,
          conditions: p.conditionsModule?.conditions || [],
          interventions: (p.armsInterventionsModule?.interventions || []).map((i: { name?: string }) => i.name || ''),
          relevance_score: 50,
          eligibility_overall: eligOverall,
          eligibility_plain: 'Review full eligibility criteria on ClinicalTrials.gov',
          criterion_checks: [],
          contact_name: contacts[0]?.name || null,
          contact_email: contacts[0]?.email || null,
          contact_phone: contacts[0]?.phone || null,
          url: `https://clinicaltrials.gov/study/${nctId}`,
        }
      })

    return { trials, total_fetched: studies.length, total_after_scoring: trials.length }
  } catch {
    return { trials: [], total_fetched: 0, total_after_scoring: 0 }
  }
}

function parseAgeYears(ageStr: string): number {
  const match = ageStr.match(/(\d+)\s*(year|month|week)/i)
  if (!match) return 0
  const n = parseInt(match[1])
  const unit = match[2].toLowerCase()
  if (unit.startsWith('month')) return n / 12
  if (unit.startsWith('week')) return n / 52
  return n
}

// ─── Overall status ───────────────────────────────────────────────────────────

function deriveOverallStatus(tier1: Tier1Result, tier2: Tier2Result, tier3: Tier3Result): AnalyzeResponse['overall_status'] {
  if (tier1.drugs.some(d => d.fda_approved)) return 'FULLY_ACTIONABLE'
  if (tier1.drugs.length > 0 || tier2.trials.length > 0) return 'PARTIALLY_ACTIONABLE'
  if (tier3.pipeline.length > 0) return 'INVESTIGATIONAL_ONLY'
  return 'NOT_ACTIONABLE'
}

// ─── Main entry point ─────────────────────────────────────────────────────────

export async function staticAnalyze(
  gene: string,
  hgvs: string,
  disease: string,
  age: number | null,
  functionalClass: string | null,
): Promise<AnalyzeResponse> {
  const [tier0, tier2] = await Promise.all([
    fetchTier0(gene, hgvs),
    fetchTier2(gene, disease, age),
  ])
  const tier1 = matchTier1(gene, functionalClass)
  const tier3 = matchTier3(gene)
  const overallStatus = deriveOverallStatus(tier1, tier2, tier3)

  const fdaDrugs = tier1.drugs.filter(d => d.fda_approved).map(d => d.drug_name)
  const patientSummary = fdaDrugs.length > 0
    ? `Your ${gene} variant has FDA-approved treatment options including ${fdaDrugs.join(', ')}. Results shown here are for informational purposes only — always consult your physician.`
    : tier2.trials.length > 0
    ? `There are ${tier2.trials.length} recruiting clinical trial(s) that may be relevant to your ${gene} variant.`
    : `No FDA-approved therapies were found specifically for your ${gene} variant, but emerging research programs may be relevant.`

  return {
    patient_label: 'Patient',
    gene,
    hgvs,
    display_mutation: hgvs,
    functional_class: functionalClass,
    overall_status: overallStatus,
    tier0,
    tier1,
    tier2,
    tier3,
    enrichment: undefined,
    patient_summary: patientSummary,
    patient_next_steps: [
      'Share these results with your physician or genetic counselor.',
      'Do not start or stop any medication based solely on this report.',
    ],
    clinician_notes: [
      `Static mode — enrichment data (OMIM, GWAS, BioGRID) not available.`,
      `Tier 0 from ClinVar API. Tier 2 from ClinicalTrials.gov API.`,
    ],
  }
}
