import type { DrugEntry, SurveillanceEntry } from '../types'

interface KBEntry {
  gene: string
  match_functional_classes: string[] | null
  action_type: 'drug' | 'surveillance' | 'surgery'
  drug_name: string | null
  action: string
  fda_approved: boolean | null
  approval_year: string | null
  evidence_level: string
  line: string | null
  caveat: string | null
  source: string | null
}

const THERAPY_KB: KBEntry[] = 
[
  {
    "gene": "CFTR",
    "match_functional_classes": [
      "f508del"
    ],
    "action_type": "drug",
    "drug_name": "Elexacaftor/Tezacaftor/Ivacaftor (Trikafta)",
    "action": "Triple CFTR modulator combination targeting F508del. Corrects protein folding (elexacaftor + tezacaftor) and potentiates channel opening (ivacaftor).",
    "fda_approved": true,
    "approval_year": "2019",
    "evidence_level": "FDA_approved",
    "line": "1st-line (age ≥2)",
    "caveat": "Requires at least one F508del allele. Also approved for 177 other responsive mutations.",
    "source": "FDA NDA 212273"
  },
  {
    "gene": "CFTR",
    "match_functional_classes": [
      "gating_mutation"
    ],
    "action_type": "drug",
    "drug_name": "Ivacaftor (Kalydeco)",
    "action": "CFTR potentiator — increases channel open probability for gating mutations (G551D, R117H, and 8 others).",
    "fda_approved": true,
    "approval_year": "2012",
    "evidence_level": "FDA_approved",
    "line": "1st-line (age ≥4 months)",
    "caveat": "Only for specific gating/residual function mutations. Not effective for F508del alone.",
    "source": "FDA NDA 203188"
  },
  {
    "gene": "CFTR",
    "match_functional_classes": [
      "residual_function"
    ],
    "action_type": "drug",
    "drug_name": "Ivacaftor (Kalydeco)",
    "action": "CFTR potentiator for residual function mutations including R117H.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "1st-line",
    "caveat": "R117H response varies; 5T allele status affects efficacy.",
    "source": "FDA NDA 203188 (supplemental)"
  },
  {
    "gene": "CFTR",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual pulmonary function tests (FEV1, FVC), sputum cultures, nutritional assessment, and CF center follow-up every 3 months.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "CFF_guideline",
    "line": null,
    "caveat": null,
    "source": "Cystic Fibrosis Foundation Care Guidelines"
  },
  {
    "gene": "DMD",
    "match_functional_classes": [
      "exon51_skippable"
    ],
    "action_type": "drug",
    "drug_name": "Eteplirsen (Exondys 51)",
    "action": "Antisense oligonucleotide that skips exon 51, restoring the reading frame for exon 50 deletions and other amenable mutations.",
    "fda_approved": true,
    "approval_year": "2016",
    "evidence_level": "FDA_approved",
    "line": "1st-line (ambulatory patients)",
    "caveat": "Approved under accelerated approval. ~13% of DMD patients are amenable.",
    "source": "FDA NDA 206488"
  },
  {
    "gene": "DMD",
    "match_functional_classes": [
      "exon51_skippable"
    ],
    "action_type": "drug",
    "drug_name": "Delandistrogene moxeparvovec (Elevidys)",
    "action": "AAV-based micro-dystrophin gene therapy. Delivers a shortened but functional dystrophin gene.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "1st-line (ages 4–5, ambulatory)",
    "caveat": "Accelerated approval for ages 4-5; full approval for ambulatory patients 4+. Pre-existing AAV antibodies may exclude.",
    "source": "FDA BLA 125781"
  },
  {
    "gene": "DMD",
    "match_functional_classes": [
      "exon53_skippable"
    ],
    "action_type": "drug",
    "drug_name": "Golodirsen (Vyondys 53)",
    "action": "Antisense oligonucleotide skipping exon 53, restoring reading frame for amenable mutations.",
    "fda_approved": true,
    "approval_year": "2019",
    "evidence_level": "FDA_approved",
    "line": "1st-line",
    "caveat": "~8% of DMD patients amenable to exon 53 skipping.",
    "source": "FDA NDA 211970"
  },
  {
    "gene": "DMD",
    "match_functional_classes": [
      "exon53_skippable"
    ],
    "action_type": "drug",
    "drug_name": "Viltolarsen (Viltepso)",
    "action": "Antisense oligonucleotide skipping exon 53.",
    "fda_approved": true,
    "approval_year": "2020",
    "evidence_level": "FDA_approved",
    "line": "1st-line",
    "caveat": "Alternative to golodirsen for exon 53-amenable mutations.",
    "source": "FDA NDA 213026"
  },
  {
    "gene": "DMD",
    "match_functional_classes": [
      "exon45_skippable"
    ],
    "action_type": "drug",
    "drug_name": "Casimersen (Amondys 45)",
    "action": "Antisense oligonucleotide skipping exon 45.",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "1st-line",
    "caveat": "~8% of DMD patients amenable to exon 45 skipping.",
    "source": "FDA NDA 213977"
  },
  {
    "gene": "DMD",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Deflazacort (Emflaza) / Prednisone",
    "action": "Corticosteroid therapy slows disease progression in all DMD patients regardless of mutation.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "Standard of care",
    "caveat": "Deflazacort preferred over prednisone (less weight gain). Start at diagnosis.",
    "source": "FDA NDA 208684"
  },
  {
    "gene": "SOD1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Tofersen (Qalsody)",
    "action": "Antisense oligonucleotide targeting SOD1 mRNA, reducing toxic SOD1 protein levels in ALS patients with SOD1 mutations.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "1st-line for SOD1-ALS",
    "caveat": "Intrathecal injection every 4 weeks after loading doses. Requires confirmed SOD1 pathogenic variant.",
    "source": "FDA NDA 215887"
  },
  {
    "gene": "SMN1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Nusinersen (Spinraza)",
    "action": "Antisense oligonucleotide that modifies SMN2 pre-mRNA splicing to increase full-length SMN protein production.",
    "fda_approved": true,
    "approval_year": "2016",
    "evidence_level": "FDA_approved",
    "line": "1st-line (all SMA types)",
    "caveat": "Intrathecal injection. 4 loading doses then maintenance every 4 months.",
    "source": "FDA NDA 209531"
  },
  {
    "gene": "SMN1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Risdiplam (Evrysdi)",
    "action": "Oral SMN2 splicing modifier — increases full-length SMN protein.",
    "fda_approved": true,
    "approval_year": "2020",
    "evidence_level": "FDA_approved",
    "line": "1st-line (age ≥2 months)",
    "caveat": "Oral administration advantage over nusinersen. Daily dosing.",
    "source": "FDA NDA 213535"
  },
  {
    "gene": "SMN1",
    "match_functional_classes": [
      "smn1_loss"
    ],
    "action_type": "drug",
    "drug_name": "Onasemnogene abeparvovec (Zolgensma)",
    "action": "AAV9-based gene therapy delivering functional SMN1 gene. One-time IV infusion.",
    "fda_approved": true,
    "approval_year": "2019",
    "evidence_level": "FDA_approved",
    "line": "1st-line (age <2 years)",
    "caveat": "Age limit <2 years. Most effective in pre-symptomatic or early symptomatic patients. Very high cost.",
    "source": "FDA BLA 125694"
  },
  {
    "gene": "BRCA1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Olaparib (Lynparza)",
    "action": "PARP inhibitor — exploits homologous recombination deficiency in BRCA1/2-mutant tumors (synthetic lethality).",
    "fda_approved": true,
    "approval_year": "2014",
    "evidence_level": "FDA_approved",
    "line": "Adjuvant (HER2-neg breast cancer) / maintenance (ovarian cancer)",
    "caveat": "Indicated for germline BRCA1/2 pathogenic variants. Multiple indications: breast, ovarian, pancreatic, prostate.",
    "source": "FDA NDA 206162"
  },
  {
    "gene": "BRCA2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Olaparib (Lynparza)",
    "action": "PARP inhibitor for BRCA2-mutant cancers.",
    "fda_approved": true,
    "approval_year": "2014",
    "evidence_level": "FDA_approved",
    "line": "Multiple indications",
    "caveat": "Same as BRCA1 — multiple tumor types approved.",
    "source": "FDA NDA 206162"
  },
  {
    "gene": "BRCA1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Niraparib (Zejula)",
    "action": "PARP inhibitor for BRCA1/2-mutant ovarian cancer maintenance therapy.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "Maintenance (ovarian cancer)",
    "caveat": "Also approved for HRD-positive tumors regardless of BRCA status.",
    "source": "FDA NDA 208447"
  },
  {
    "gene": "BRCA1",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram starting age 25-30. Consider risk-reducing mastectomy and/or salpingo-oophorectomy (RRSO) after childbearing.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": "RRSO recommended by age 35-40 for BRCA1; 40-45 for BRCA2.",
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "BRCA2",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram starting age 25-30. Consider RRSO after childbearing. Prostate cancer screening for males starting age 40.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "MLH1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Pembrolizumab (Keytruda) — MSI-H/dMMR tumors",
    "action": "PD-1 checkpoint inhibitor with high response rates in MSI-H/dMMR tumors arising in Lynch syndrome patients.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "1st-line (MSI-H solid tumors)",
    "caveat": "Tumor-agnostic approval for MSI-H/dMMR. Requires tumor testing to confirm MSI-H status.",
    "source": "FDA NDA 125514 (tumor-agnostic)"
  },
  {
    "gene": "MLH1",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Colonoscopy every 1-2 years starting age 20-25. Annual gynecologic exam + endometrial sampling for females. Consider aspirin chemoprevention.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "TTR",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Tafamidis (Vyndaqel/Vyndamax)",
    "action": "TTR stabilizer — prevents tetramer dissociation and amyloid fibril formation. Reduces CV mortality in TTR cardiomyopathy.",
    "fda_approved": true,
    "approval_year": "2019",
    "evidence_level": "FDA_approved",
    "line": "1st-line (TTR cardiomyopathy)",
    "caveat": "Approved for both hereditary and wild-type TTR cardiomyopathy.",
    "source": "FDA NDA 211996"
  },
  {
    "gene": "TTR",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Patisiran (Onpattro)",
    "action": "siRNA therapy silencing TTR gene expression — reduces TTR protein by ~80%. For hereditary TTR polyneuropathy.",
    "fda_approved": true,
    "approval_year": "2018",
    "evidence_level": "FDA_approved",
    "line": "1st-line (TTR polyneuropathy)",
    "caveat": "IV infusion every 3 weeks. Requires premedication.",
    "source": "FDA NDA 210922"
  },
  {
    "gene": "TTR",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Vutrisiran (Amvuttra)",
    "action": "Next-generation siRNA for hereditary TTR polyneuropathy — subcutaneous injection every 3 months.",
    "fda_approved": true,
    "approval_year": "2022",
    "evidence_level": "FDA_approved",
    "line": "1st-line (TTR polyneuropathy)",
    "caveat": "More convenient dosing than patisiran (SC q3m vs IV q3w).",
    "source": "FDA NDA 215515"
  },
  {
    "gene": "HBB",
    "match_functional_classes": [
      "sickle_cell"
    ],
    "action_type": "drug",
    "drug_name": "Exagamglogene autotemcel (Casgevy)",
    "action": "CRISPR-Cas9 gene therapy — edits BCL11A enhancer to reactivate fetal hemoglobin (HbF), compensating for defective HbS.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "Curative intent (age ≥12)",
    "caveat": "First CRISPR therapy approved by FDA. Requires myeloablative conditioning. One-time treatment.",
    "source": "FDA BLA 761343"
  },
  {
    "gene": "HBB",
    "match_functional_classes": [
      "beta_thal"
    ],
    "action_type": "drug",
    "drug_name": "Betibeglogene spartacus (Zynteglo)",
    "action": "Lentiviral gene therapy adding functional beta-globin gene — curative intent for transfusion-dependent beta-thalassemia.",
    "fda_approved": true,
    "approval_year": "2022",
    "evidence_level": "FDA_approved",
    "line": "Curative intent (age ≥12)",
    "caveat": "Requires myeloablative conditioning. One-time treatment.",
    "source": "FDA BLA 125703"
  },
  {
    "gene": "LDLR",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Evolocumab (Repatha)",
    "action": "PCSK9 inhibitor — prevents LDLR degradation, dramatically lowering LDL-C (50-60% reduction on top of statins).",
    "fda_approved": true,
    "approval_year": "2015",
    "evidence_level": "FDA_approved",
    "line": "Add-on to statins (HeFH/HoFH)",
    "caveat": "SC injection every 2 or 4 weeks. Also approved for ASCVD risk reduction.",
    "source": "FDA BLA 125522"
  },
  {
    "gene": "LDLR",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Inclisiran (Leqvio)",
    "action": "siRNA targeting PCSK9 mRNA — twice-yearly SC injection for LDL-C reduction in FH.",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "Add-on to statins",
    "caveat": "Twice-yearly dosing advantage. Administered in clinical setting.",
    "source": "FDA NDA 214012"
  },
  {
    "gene": "MYBPC3",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Mavacamten (Camzyos)",
    "action": "Cardiac myosin inhibitor — reduces hypercontractility in obstructive HCM. First disease-specific HCM therapy.",
    "fda_approved": true,
    "approval_year": "2022",
    "evidence_level": "FDA_approved",
    "line": "1st-line (obstructive HCM, NYHA II-III)",
    "caveat": "REMS program required. Avoid with strong CYP2C19 inhibitors. Echocardiographic monitoring required.",
    "source": "FDA NDA 214998"
  },
  {
    "gene": "MYH7",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Mavacamten (Camzyos)",
    "action": "Cardiac myosin inhibitor for obstructive HCM regardless of underlying mutation.",
    "fda_approved": true,
    "approval_year": "2022",
    "evidence_level": "FDA_approved",
    "line": "1st-line (obstructive HCM)",
    "caveat": "Same REMS and monitoring requirements as for MYBPC3.",
    "source": "FDA NDA 214998"
  },
  {
    "gene": "NF1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Selumetinib (Koselugo)",
    "action": "MEK1/2 inhibitor — reduces plexiform neurofibroma volume in pediatric NF1 patients.",
    "fda_approved": true,
    "approval_year": "2020",
    "evidence_level": "FDA_approved",
    "line": "1st-line (symptomatic plexiform neurofibromas, age ≥2)",
    "caveat": "Oral twice daily. Requires ophthalmologic monitoring.",
    "source": "FDA NDA 213756"
  },
  {
    "gene": "VHL",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Belzutifan (Welireg)",
    "action": "HIF-2α inhibitor — targets the VHL/HIF pathway. Approved for VHL disease-associated tumors (RCC, CNS hemangioblastomas, pNETs).",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "1st-line (VHL disease-associated tumors)",
    "caveat": "Oral daily. Monitor for anemia and hypoxia.",
    "source": "FDA NDA 215383"
  },
  {
    "gene": "FXN",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Omaveloxolone (Skyclarys)",
    "action": "Nrf2 activator — first FDA-approved treatment for Friedreich ataxia. Reduces neurological decline.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "1st-line (age ≥16)",
    "caveat": "Oral daily. Monitor liver enzymes. Significant drug interactions.",
    "source": "FDA NDA 216718"
  },
  {
    "gene": "RET",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Selpercatinib (Retevmo)",
    "action": "Selective RET kinase inhibitor for RET-altered cancers including MEN2-associated medullary thyroid cancer.",
    "fda_approved": true,
    "approval_year": "2020",
    "evidence_level": "FDA_approved",
    "line": "1st-line (advanced/metastatic MTC)",
    "caveat": "Oral twice daily. Also approved for RET fusion-positive NSCLC and thyroid cancer.",
    "source": "FDA NDA 213246"
  },
  {
    "gene": "RET",
    "match_functional_classes": ["ret_men2a", "ret_men2b"],
    "action_type": "surgery",
    "drug_name": null,
    "action": "Prophylactic thyroidectomy — timing based on RET codon risk category. MEN2B (M918T): within first 6 months of life. MEN2A high-risk (C634): by age 5.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "ATA_guideline",
    "line": null,
    "caveat": "Risk stratification by specific codon determines urgency.",
    "source": "ATA Guidelines for Medullary Thyroid Cancer 2015"
  },
  {
    "gene": "MSH2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Pembrolizumab (Keytruda) — MSI-H/dMMR tumors",
    "action": "PD-1 checkpoint inhibitor. Tumor-agnostic approval for MSI-H/dMMR tumors from Lynch syndrome.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "1st-line (MSI-H solid tumors)",
    "caveat": "Requires tumor MSI-H or dMMR confirmation.",
    "source": "FDA NDA 125514 (tumor-agnostic)"
  },
  {
    "gene": "MSH2",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Colonoscopy every 1-2 years starting age 20-25. Annual gynecologic exam + endometrial sampling (females). Aspirin chemoprevention (600mg/day shown beneficial in CAPP2 trial).",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "MSH6",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Pembrolizumab (Keytruda) — MSI-H/dMMR tumors",
    "action": "PD-1 checkpoint inhibitor for MSI-H/dMMR tumors.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "1st-line (MSI-H solid tumors)",
    "caveat": "MSH6 Lynch carriers have higher endometrial cancer risk than colorectal.",
    "source": "FDA NDA 125514 (tumor-agnostic)"
  },
  {
    "gene": "MSH6",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Colonoscopy every 2-3 years starting age 30-35 (later onset than MLH1/MSH2). Gynecologic surveillance starting age 30-35.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "PMS2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Pembrolizumab (Keytruda) — MSI-H/dMMR tumors",
    "action": "PD-1 checkpoint inhibitor for MSI-H/dMMR tumors.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "1st-line (MSI-H solid tumors)",
    "caveat": "PMS2 Lynch has lower penetrance than MLH1/MSH2.",
    "source": "FDA NDA 125514 (tumor-agnostic)"
  },
  {
    "gene": "PMS2",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Colonoscopy every 2-3 years starting age 35-40. Gynecologic surveillance as per MSH6.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "PALB2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Olaparib (Lynparza)",
    "action": "PARP inhibitor — PALB2 functions in HR pathway with BRCA1/2; PALB2-mutant tumors show similar HRD sensitivity.",
    "fda_approved": true,
    "approval_year": "2022",
    "evidence_level": "FDA_approved",
    "line": "Adjuvant (HER2-neg early breast cancer with gBRCA/PALB2)",
    "caveat": "FDA approval for germline PALB2 pathogenic variants in breast cancer (OlympiA trial extension).",
    "source": "FDA NDA 206162 (supplemental)"
  },
  {
    "gene": "PALB2",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram starting age 30. Consider risk-reducing mastectomy discussion.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "ATM",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Olaparib (Lynparza)",
    "action": "PARP inhibitor — ATM-mutant pancreatic and prostate cancers show HRD sensitivity.",
    "fda_approved": true,
    "approval_year": "2019",
    "evidence_level": "FDA_approved",
    "line": "Maintenance (mCRPC, pancreatic cancer)",
    "caveat": "Approved for gATM in mCRPC (PROfound trial) and pancreatic cancer.",
    "source": "FDA NDA 206162 (supplemental)"
  },
  {
    "gene": "ATM",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram (females) starting age 40. Pancreatic cancer surveillance (EUS/MRI) starting age 50 or 10 years before youngest affected relative.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "CHEK2",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram starting age 40 (or earlier based on family history). Colonoscopy every 5 years starting age 40.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": "Moderate-risk gene — no approved targeted therapy; management is surveillance-based.",
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "F8",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Emicizumab (Hemlibra)",
    "action": "Bispecific antibody mimicking FVIIIa — bridges FIXa and FX. Prophylaxis for Hemophilia A with or without inhibitors.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "1st-line prophylaxis",
    "caveat": "Subcutaneous injection. Dramatically reduces bleed rate. Does not replace FVIII for acute bleeds.",
    "source": "FDA BLA 761109"
  },
  {
    "gene": "F8",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Fitusiran (Alhemo)",
    "action": "siRNA targeting antithrombin — rebalances coagulation. Subcutaneous monthly for Hemophilia A/B with or without inhibitors.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "Prophylaxis (with/without inhibitors)",
    "caveat": "Monthly SC injection. Risk of thrombotic events — strict monitoring protocol.",
    "source": "FDA NDA 761174"
  },
  {
    "gene": "F9",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Etranacogene dezaparvovec (Hemgenix)",
    "action": "AAV5-based gene therapy delivering high-activity FIX-Padua variant. One-time IV infusion providing sustained FIX expression.",
    "fda_approved": true,
    "approval_year": "2022",
    "evidence_level": "FDA_approved",
    "line": "Curative intent (adults, no inhibitors)",
    "caveat": "One-time treatment. Pre-existing AAV5 antibodies may exclude. Most expensive drug approved (~$3.5M).",
    "source": "FDA BLA 125736"
  },
  {
    "gene": "F9",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Fitusiran (Alhemo)",
    "action": "siRNA targeting antithrombin for Hemophilia B prophylaxis.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "Prophylaxis",
    "caveat": "Same monitoring as for F8.",
    "source": "FDA NDA 761174"
  },
  {
    "gene": "GBA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Imiglucerase (Cerezyme)",
    "action": "Enzyme replacement therapy — recombinant glucocerebrosidase for Gaucher disease type 1 and 3.",
    "fda_approved": true,
    "approval_year": "1994",
    "evidence_level": "FDA_approved",
    "line": "1st-line (symptomatic Gaucher type 1/3)",
    "caveat": "IV infusion every 2 weeks. Most widely used ERT for Gaucher.",
    "source": "FDA BLA 103361"
  },
  {
    "gene": "GBA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Eliglustat (Cerdelga)",
    "action": "Oral substrate reduction therapy — inhibits glucosylceramide synthase. First oral therapy for Gaucher type 1.",
    "fda_approved": true,
    "approval_year": "2014",
    "evidence_level": "FDA_approved",
    "line": "1st-line (Gaucher type 1, adult, CYP2D6 metabolizers)",
    "caveat": "Requires CYP2D6 genotyping. Not for poor metabolizers. Oral advantage over ERT.",
    "source": "FDA NDA 205494"
  },
  {
    "gene": "GBA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Venglustat / Ambroxol",
    "action": "GBA chaperone therapy (ambroxol) and GCS inhibitor (venglustat) under investigation for GBA-associated Parkinson disease prevention.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "clinical_trial",
    "line": "Investigational (GBA-PD)",
    "caveat": "GBA carriers have 5-10x increased Parkinson risk. Preventive trials enrolling asymptomatic GBA carriers.",
    "source": "MOVES-PD trial; Ambroxol-PD trials"
  },
  {
    "gene": "HTT",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Tetrabenazine (Xenazine) / Deutetrabenazine (Austedo)",
    "action": "VMAT2 inhibitors — reduce involuntary choreiform movements (chorea) in Huntington disease.",
    "fda_approved": true,
    "approval_year": "2008",
    "evidence_level": "FDA_approved",
    "line": "Symptomatic (chorea)",
    "caveat": "Does not slow disease progression. Deutetrabenazine has better tolerability and twice-daily dosing.",
    "source": "FDA NDA 021894 (tetrabenazine); FDA NDA 208082 (deutetrabenazine)"
  },
  {
    "gene": "HTT",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Genetic counseling, annual neurological assessment, speech/occupational/physical therapy. Enroll in PREDICT-HD registry if pre-manifest.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "HDSA_guideline",
    "line": null,
    "caveat": "No disease-modifying therapy approved yet. Multiple trials ongoing (WVE-003, AMT-130).",
    "source": "HDSA Standards of Care 2023"
  },
  {
    "gene": "PCSK9",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Evolocumab (Repatha)",
    "action": "PCSK9 inhibitor monoclonal antibody — prevents LDLR degradation, reducing LDL-C by 50-60%.",
    "fda_approved": true,
    "approval_year": "2015",
    "evidence_level": "FDA_approved",
    "line": "1st-line add-on to statins (HoFH/HeFH)",
    "caveat": "For gain-of-function PCSK9 variants causing FH.",
    "source": "FDA BLA 125522"
  },
  {
    "gene": "PCSK9",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Alirocumab (Praluent)",
    "action": "PCSK9 inhibitor — biweekly SC injection for LDL-C reduction in FH.",
    "fda_approved": true,
    "approval_year": "2015",
    "evidence_level": "FDA_approved",
    "line": "Add-on to statins",
    "caveat": null,
    "source": "FDA BLA 125559"
  },
  {
    "gene": "TSC1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Everolimus (Afinitor/Votubia)",
    "action": "mTORC1 inhibitor — reduces SEGA (subependymal giant cell astrocytoma), renal AMLs, and pulmonary LAM in TSC.",
    "fda_approved": true,
    "approval_year": "2010",
    "evidence_level": "FDA_approved",
    "line": "1st-line (SEGA, renal AML, LAM)",
    "caveat": "Multiple TSC indications: SEGA (age ≥1), renal AML, partial-onset seizures (adjunctive). Oral daily.",
    "source": "FDA NDA 022334"
  },
  {
    "gene": "TSC2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Everolimus (Afinitor/Votubia)",
    "action": "mTORC1 inhibitor for TSC-associated tumors. TSC2 mutations generally cause more severe disease than TSC1.",
    "fda_approved": true,
    "approval_year": "2010",
    "evidence_level": "FDA_approved",
    "line": "1st-line (SEGA, renal AML, seizures)",
    "caveat": "Same indications as TSC1.",
    "source": "FDA NDA 022334"
  },
  {
    "gene": "TSC1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Sirolimus (Rapamune)",
    "action": "mTOR inhibitor — approved for pulmonary LAM (lymphangioleiomyomatosis) in TSC.",
    "fda_approved": true,
    "approval_year": "2015",
    "evidence_level": "FDA_approved",
    "line": "Pulmonary LAM",
    "caveat": null,
    "source": "FDA NDA 021110 (LAM indication)"
  },
  {
    "gene": "TSC2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Sirolimus (Rapamune)",
    "action": "mTOR inhibitor for pulmonary LAM in TSC.",
    "fda_approved": true,
    "approval_year": "2015",
    "evidence_level": "FDA_approved",
    "line": "Pulmonary LAM",
    "caveat": null,
    "source": "FDA NDA 021110 (LAM indication)"
  },
  {
    "gene": "PTEN",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram starting age 30-35. Thyroid ultrasound annually. Colonoscopy every 5 years starting age 35. Annual skin and urology surveillance.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": "No approved targeted therapy for PTEN germline. PI3K/AKT/mTOR inhibitors active in PTEN-deficient tumors.",
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "APC",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Celecoxib (Celebrex)",
    "action": "COX-2 inhibitor — reduces colorectal polyp burden in FAP as adjunct to endoscopic surveillance.",
    "fda_approved": true,
    "approval_year": "1999",
    "evidence_level": "FDA_approved",
    "line": "Adjunct to endoscopy (FAP)",
    "caveat": "Does not replace colectomy. Reduces polyp number but not a curative strategy.",
    "source": "FDA NDA 020998 (FAP indication)"
  },
  {
    "gene": "APC",
    "match_functional_classes": null,
    "action_type": "surgery",
    "drug_name": null,
    "action": "Prophylactic colectomy — recommended by age 20-25 or when polyps become unmanageable. Options: total proctocolectomy with IPAA or subtotal colectomy with IRA.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": "Timing depends on polyp burden, genotype, and patient preference.",
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "VHL",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual ophthalmologic exam (retinal hemangioblastomas). Brain/spine MRI every 2 years. Annual abdominal ultrasound. Annual blood pressure monitoring.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "VHL_Alliance_guideline",
    "line": null,
    "caveat": null,
    "source": "VHL Alliance Clinical Surveillance Recommendations 2021"
  },
  {
    "gene": "FBN1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Losartan / Atenolol",
    "action": "ARB (losartan) or beta-blocker (atenolol) to slow aortic root dilation and reduce risk of aortic dissection in Marfan syndrome.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "guideline_recommended",
    "line": "1st-line (aortic dilation)",
    "caveat": "Off-label use but strongly recommended by guidelines. Reduces TGF-β signaling (losartan). Target HR <100 bpm (atenolol).",
    "source": "2010 ACCF/AHA Thoracic Aortic Disease Guidelines"
  },
  {
    "gene": "FBN1",
    "match_functional_classes": null,
    "action_type": "surgery",
    "drug_name": null,
    "action": "Prophylactic aortic root surgery when aortic root diameter reaches 4.5-5.0cm (or 4.0cm with family history of dissection). Valve-sparing root replacement preferred.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "ACCF_AHA_guideline",
    "line": null,
    "caveat": "Threshold lower for women, rapid growth (>0.5cm/year), or family history of dissection.",
    "source": "2022 ACC/AHA Aortic Disease Guidelines"
  },
  {
    "gene": "PKD1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Tolvaptan (Jynarque)",
    "action": "Vasopressin V2 receptor antagonist — slows kidney cyst growth and preserves GFR in rapidly progressive ADPKD.",
    "fda_approved": true,
    "approval_year": "2018",
    "evidence_level": "FDA_approved",
    "line": "1st-line (adults with rapidly progressive ADPKD)",
    "caveat": "REMS program required due to hepatotoxicity risk. Requires baseline liver function. Monthly LFT monitoring.",
    "source": "FDA NDA 204441"
  },
  {
    "gene": "PKD2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Tolvaptan (Jynarque)",
    "action": "Vasopressin V2 receptor antagonist for ADPKD — PKD2 mutations cause slower progression than PKD1.",
    "fda_approved": true,
    "approval_year": "2018",
    "evidence_level": "FDA_approved",
    "line": "Adults with rapidly progressive ADPKD",
    "caveat": "PKD2 ADPKD is generally milder; confirm rapidly progressive criteria before prescribing.",
    "source": "FDA NDA 204441"
  },
  {
    "gene": "HFE",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Therapeutic Phlebotomy",
    "action": "Regular blood removal (500mL every 1-2 weeks) to reduce iron overload — first-line treatment for HFE hemochromatosis.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "AASLD_guideline",
    "line": "1st-line",
    "caveat": "Initiated when ferritin >300 ng/mL (males) or >200 ng/mL (females). Target ferritin 50-100 ng/mL.",
    "source": "AASLD Practice Guidelines: Hemochromatosis 2011"
  },
  {
    "gene": "ATP7B",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Trientine (Syprine) / D-penicillamine",
    "action": "Copper chelation therapy — removes excess copper in Wilson disease. Trientine preferred (fewer side effects).",
    "fda_approved": true,
    "approval_year": "1969",
    "evidence_level": "FDA_approved",
    "line": "1st-line (symptomatic Wilson disease)",
    "caveat": "Lifelong treatment required. D-penicillamine has more side effects. Zinc used for maintenance/pre-symptomatic.",
    "source": "FDA NDA 017934 (trientine)"
  },
  {
    "gene": "ATP7B",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Zinc acetate (Galzin)",
    "action": "Blocks intestinal copper absorption — maintenance therapy and first-line for pre-symptomatic Wilson disease.",
    "fda_approved": true,
    "approval_year": "1997",
    "evidence_level": "FDA_approved",
    "line": "Maintenance / pre-symptomatic",
    "caveat": "Slower onset than chelation. Preferred for pre-symptomatic patients and pregnancy.",
    "source": "FDA NDA 019952"
  },
  {
    "gene": "TP53",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Rapid whole-body MRI (WBMRI) annually. Brain MRI annually. Breast MRI + mammogram annually starting age 20-25. Colonoscopy every 2-5 years from age 25. Avoid radiation exposure when possible.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": "Toronto Protocol or similar intensive surveillance reduces mortality. Avoid diagnostic radiation (CT scans) unless essential.",
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024; Toronto LFS Protocol"
  },
  {
    "gene": "KCNQ1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Beta-blockers (Nadolol / Propranolol)",
    "action": "Beta-adrenergic blockade reduces sympathetically triggered arrhythmias in LQT1 (KCNQ1). Nadolol preferred.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "AHA_HRS_guideline",
    "line": "1st-line (LQT1)",
    "caveat": "Avoid QT-prolonging drugs. Avoid competitive sports. ICD if prior cardiac arrest or breakthrough events on beta-blockers.",
    "source": "2022 AHA/ACC/HRS Guideline for Ventricular Arrhythmias"
  },
  {
    "gene": "KCNH2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Beta-blockers (Nadolol / Propranolol)",
    "action": "Beta-adrenergic blockade for LQT2 (KCNH2). LQT2 is particularly sensitive to auditory triggers and hypokalemia.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "AHA_HRS_guideline",
    "line": "1st-line (LQT2)",
    "caveat": "Maintain normal K+ and Mg2+. Avoid abrupt loud sounds. Mexiletine may be used as add-on.",
    "source": "2022 AHA/ACC/HRS Guideline for Ventricular Arrhythmias"
  },
  {
    "gene": "SCN5A",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Quinidine / ICD",
    "action": "Quinidine blocks transient outward current (Ito) in Brugada syndrome — reduces VF recurrence. ICD is standard for symptomatic patients.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "AHA_HRS_guideline",
    "line": "ICD (symptomatic) / Quinidine (adjunct)",
    "caveat": "Avoid sodium channel blockers, fever, and excess alcohol. Antipyretics promptly for any fever.",
    "source": "2022 AHA/ACC/HRS Guideline for Ventricular Arrhythmias; HRS Expert Consensus 2019"
  },
  {
    "gene": "LMNA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "ICD (Implantable Cardioverter-Defibrillator) + Heart Failure Therapy",
    "action": "ICD strongly recommended due to high risk of sudden cardiac death in LMNA cardiomyopathy even with preserved EF. Standard HF therapy (ACEi/ARB, beta-blocker) for DCM.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "ESC_guideline",
    "line": "1st-line (LMNA cardiomyopathy)",
    "caveat": "ICD recommended when ≥2 risk factors: NSVT, LVEF <45%, male sex, non-missense mutation. Very high risk for sudden death.",
    "source": "2023 ESC Guidelines for Cardiomyopathies"
  },
  {
    "gene": "PKP2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Sotalol / Amiodarone + ICD",
    "action": "Antiarrhythmic therapy plus ICD for ARVC (arrhythmogenic right ventricular cardiomyopathy). Beta-blockers for all symptomatic patients.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "AHA_HRS_guideline",
    "line": "ICD + antiarrhythmics",
    "caveat": "Restrict competitive athletics — exercise worsens ARVC progression. ICD for sustained VT/VF or high-risk features.",
    "source": "2019 HRS Expert Consensus on ARVC"
  },
  {
    "gene": "COL3A1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Celiprolol",
    "action": "Beta-1 blocker — reduces arterial rupture risk in vascular EDS (COL3A1). Shown to reduce serious complications in clinical trial.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "clinical_trial",
    "line": "1st-line (vascular EDS)",
    "caveat": "Off-label in the US. Supported by randomized trial showing ~50% reduction in complications. Target HR <70 bpm.",
    "source": "Ong et al., NEJM 2010; ESC/ERN Vascular EDS Guidelines"
  },
  {
    "gene": "RB1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Abemaciclib (Verzenio) — CDK4/6 inhibitor",
    "action": "CDK4/6 inhibitor — RB1-pathway targeted therapy for RB1-mutant cancers (e.g. breast cancer with germline RB1 variants).",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "Adjuvant (HR+/HER2- breast cancer)",
    "caveat": "Not specifically indicated for germline RB1, but RB pathway is directly relevant. Discuss with oncologist.",
    "source": "FDA NDA 208716"
  },
  {
    "gene": "RB1",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Ophthalmologic exam under anesthesia every 3-4 weeks until age 3, then less frequently. Annual full-body exam for secondary malignancies. Brain MRI if trilateral retinoblastoma suspected.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "COG_guideline",
    "line": null,
    "caveat": "Siblings of affected children should be screened at birth.",
    "source": "Children's Oncology Group RB Surveillance Guidelines"
  },
  {
    "gene": "STK11",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Upper and lower GI endoscopy every 2-3 years from age 8-10. Annual breast MRI + mammogram from age 25. Pancreatic MRI/EUS from age 30-35. Annual pelvic exam (females).",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": "Very high lifetime cancer risk (breast 45%, colorectal 39%, pancreatic 11-36%).",
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "CDH1",
    "match_functional_classes": null,
    "action_type": "surgery",
    "drug_name": null,
    "action": "Prophylactic total gastrectomy recommended by age 20-30 for pathogenic CDH1 variants. Diffuse gastric cancer risk >70% by age 80.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "IGCLC_guideline",
    "line": null,
    "caveat": "Endoscopic surveillance is insufficient — diffuse-type tumors are endoscopically occult. PTG is life-saving.",
    "source": "IGCLC CDH1 Guidelines 2020; NCCN v2.2024"
  },
  {
    "gene": "CDH1",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual breast MRI + mammogram (females, CDH1 associated with lobular breast cancer, ~40-54% lifetime risk). Chromoendoscopy before gastrectomy decision.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "NCCN_guideline",
    "line": null,
    "caveat": null,
    "source": "NCCN Guidelines Genetic/Familial High-Risk Assessment v2.2024"
  },
  {
    "gene": "HNF1A",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Sulfonylureas (Gliclazide / Glipizide)",
    "action": "Sulfonylureas are dramatically effective in HNF1A-MODY (MODY3) — low-dose sulfonylureas achieve glycemic control in most patients, replacing insulin.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "precision_medicine_guideline",
    "line": "1st-line (HNF1A-MODY)",
    "caveat": "CRITICAL: Patients incorrectly diagnosed as T1D or T2D may be on insulin unnecessarily. Genetic diagnosis enables treatment switch. Hypoglycemia risk is real — start low dose.",
    "source": "Pearson et al., NEJM 2003; ISPAD MODY Guidelines 2022"
  },
  {
    "gene": "GCK",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "No pharmacological treatment needed in most GCK-MODY. Mild stable hyperglycemia (fasting 5.5-8 mmol/L) — does not progress and does not cause microvascular complications.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "ISPAD_guideline",
    "line": null,
    "caveat": "CRITICAL: Do not treat with insulin or sulfonylureas unless pregnant. Discontinuing treatment in misdiagnosed patients is the intervention.",
    "source": "ISPAD MODY Clinical Practice Consensus Guidelines 2022"
  },
  {
    "gene": "MYBPC3",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Aficamten (investigational)",
    "action": "Next-generation cardiac myosin inhibitor — Phase 3 data (SEQUOIA-HCM) showing superior reduction in LVOT gradient with better tolerability than mavacamten.",
    "fda_approved": false,
    "approval_year": null,
    "evidence_level": "clinical_trial",
    "line": "Investigational (obstructive HCM)",
    "caveat": "FDA submission expected 2024-2025. May offer broader access without REMS requirements.",
    "source": "SEQUOIA-HCM trial; Cytokinetics NDA filing 2024"
  },
  {
    "gene": "MYBPC3",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual echocardiogram. Ambulatory ECG monitoring. Avoid high-intensity competitive athletics. Family screening with echo + genetic testing.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "AHA_ACC_guideline",
    "line": null,
    "caveat": null,
    "source": "2020 AHA/ACC HCM Guidelines"
  },
  {
    "gene": "MYH7",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual echocardiogram. Ambulatory ECG. Avoid competitive sports. Family cascade screening.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "AHA_ACC_guideline",
    "line": null,
    "caveat": null,
    "source": "2020 AHA/ACC HCM Guidelines"
  },
  {
    "gene": "HBB",
    "match_functional_classes": [
      "sickle_cell"
    ],
    "action_type": "drug",
    "drug_name": "Hydroxyurea (Siklos/Droxia)",
    "action": "Induces fetal hemoglobin (HbF) production, reducing sickling frequency, pain crises, ACS, and transfusions.",
    "fda_approved": true,
    "approval_year": "1998",
    "evidence_level": "FDA_approved",
    "line": "1st-line (age ≥2, sickle cell disease)",
    "caveat": "Requires CBC monitoring. Teratogenic — contraception required. Most cost-effective SCD therapy.",
    "source": "FDA NDA 021276"
  },
  {
    "gene": "HBB",
    "match_functional_classes": [
      "sickle_cell"
    ],
    "action_type": "drug",
    "drug_name": "L-glutamine (Endari)",
    "action": "Reduces oxidative stress in sickle red cells — decreases pain crises frequency.",
    "fda_approved": true,
    "approval_year": "2017",
    "evidence_level": "FDA_approved",
    "line": "Add-on therapy (age ≥5)",
    "caveat": "Modest effect size. Oral powder twice daily. Often used with hydroxyurea.",
    "source": "FDA NDA 208587"
  },
  {
    "gene": "HBB",
    "match_functional_classes": [
      "sickle_cell"
    ],
    "action_type": "drug",
    "drug_name": "Lovotibeglogene autotemcel (Lyfgenia)",
    "action": "Lentiviral gene therapy adding anti-sickling βT87Q-globin gene — alternative gene therapy to Casgevy.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "Curative intent (age ≥12)",
    "caveat": "Requires myeloablative conditioning. Risk of hematologic malignancy (monitor long-term). Different mechanism to Casgevy.",
    "source": "FDA BLA 125709"
  },
  {
    "gene": "KCNJ11",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Sulfonylureas (Glibenclamide / Glipizide)",
    "action": "KCNJ11 activating mutations cause neonatal diabetes by keeping ATP-sensitive K+ channels open. Sulfonylureas close these channels independently of ATP, allowing insulin secretion. Most patients can completely transfer from insulin injections to oral sulfonylureas — one of the most dramatic precision medicine successes in diabetes.",
    "fda_approved": true,
    "approval_year": "off-label precision use",
    "evidence_level": "precision_medicine_guideline",
    "line": "1st-line (KCNJ11 neonatal diabetes — replaces insulin)",
    "caveat": "Transfer from insulin to sulfonylurea requires specialist supervision. Glibenclamide preferred in children. Success rate ~90% for activating KCNJ11 mutations.",
    "source": "Pearson et al. NEJM 2006; ISPAD MODY Guidelines 2022"
  },
  {
    "gene": "ABCC8",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Sulfonylureas (Glibenclamide) / Diazoxide",
    "action": "ABCC8 encodes SUR1, the regulatory subunit of ATP-sensitive K+ channels. Activating mutations → neonatal diabetes treatable with sulfonylureas (same mechanism as KCNJ11). Loss-of-function mutations → congenital hyperinsulinism treatable with diazoxide (opens K+ channels to suppress insulin).",
    "fda_approved": true,
    "approval_year": "off-label precision use",
    "evidence_level": "precision_medicine_guideline",
    "line": "1st-line (mutation-direction dependent)",
    "caveat": "Treatment direction depends on mutation type: activating = sulfonylurea; loss-of-function = diazoxide. Genetic testing result is essential before prescribing.",
    "source": "Ellard et al. Diabetologia 2007; ISPAD Guidelines 2022"
  },
  {
    "gene": "PHEX",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Burosumab (Crysvita)",
    "action": "Anti-FGF23 monoclonal antibody. PHEX loss-of-function causes excess FGF23, leading to phosphate wasting and rickets. Burosumab neutralizes FGF23, restoring phosphate reabsorption and normalizing bone mineralization.",
    "fda_approved": true,
    "approval_year": "2018",
    "evidence_level": "FDA_approved",
    "line": "1st-line (XLH, age ≥1 year)",
    "caveat": "First-ever approved therapy for XLH. Monitor serum phosphate and urine calcium. Contraindicated with oral phosphate/active vitamin D.",
    "source": "FDA BLA 761069"
  },
  {
    "gene": "GAA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Avalglucosidase alfa (Nexviazyme)",
    "action": "Next-generation enzyme replacement therapy (ERT) with enhanced M6P receptor targeting. GAA mutations cause lysosomal glycogen accumulation in muscle. Avalglucosidase alfa replaces deficient acid alpha-glucosidase with higher uptake efficiency than first-gen alglucosidase.",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "1st-line (Pompe disease, all ages)",
    "caveat": "Preferred over alglucosidase alfa (Myozyme) due to superior clinical outcomes in COMET trial. Infusion reactions possible — premedicate.",
    "source": "FDA BLA 761136"
  },
  {
    "gene": "GAA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Alglucosidase alfa (Myozyme / Lumizyme)",
    "action": "First-generation enzyme replacement therapy for Pompe disease. Recombinant human acid alpha-glucosidase delivered IV to clear lysosomal glycogen accumulation in cardiac and skeletal muscle.",
    "fda_approved": true,
    "approval_year": "2006",
    "evidence_level": "FDA_approved",
    "line": "Alternative ERT (if Nexviazyme unavailable)",
    "caveat": "Largely superseded by avalglucosidase alfa. Still used for patients stable on alglucosidase or in access-limited settings.",
    "source": "FDA BLA 125141"
  },
  {
    "gene": "GAA",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Cipaglucosidase alfa + miglustat (Pombiliti + Opfolda)",
    "action": "ERT + pharmacological chaperone combination. Miglustat stabilizes cipaglucosidase alfa in circulation, improving delivery to lysosomes. Approved for late-onset Pompe disease in adults not yet on ERT or switching.",
    "fda_approved": true,
    "approval_year": "2023",
    "evidence_level": "FDA_approved",
    "line": "1st-line (late-onset Pompe, adults)",
    "caveat": "Oral miglustat taken with IV cipaglucosidase infusion. Not approved for infantile-onset Pompe.",
    "source": "FDA NDA 216139 + BLA 761261"
  },
  {
    "gene": "ACTA2",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Losartan / Beta-blockers (Atenolol)",
    "action": "ACTA2 mutations cause smooth muscle cell dysfunction leading to thoracic aortic aneurysm. Losartan (ARB) reduces aortic wall stress via TGF-β pathway modulation. Beta-blockers reduce hemodynamic stress on the aortic wall.",
    "fda_approved": false,
    "approval_year": "off-label",
    "evidence_level": "expert_guideline",
    "line": "1st-line medical management (ACTA2-TAAD)",
    "caveat": "No RCT specific to ACTA2. Extrapolated from Marfan/FBN1 evidence and expert consensus. Prophylactic aortic surgery at smaller diameters than sporadic aneurysm.",
    "source": "AHA/ACC Thoracic Aortic Disease Guidelines 2022"
  },
  {
    "gene": "ACTA2",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Annual aortic imaging (MRI preferred). Prophylactic aortic root surgery at 4.5 cm (lower threshold than sporadic aneurysm due to rapid progression risk). Screen first-degree relatives. Avoid isometric exercise and competitive sports.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "expert_guideline",
    "line": null,
    "caveat": null,
    "source": "AHA/ACC Thoracic Aortic Disease Guidelines 2022"
  },
  {
    "gene": "LDLRAP1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Lomitapide (Juxtapid)",
    "action": "MTP inhibitor reduces hepatic VLDL/LDL production. Approved for homozygous FH — effective regardless of LDL receptor pathway mutation (LDLR, APOB, PCSK9, LDLRAP1) since it acts upstream of LDL receptor.",
    "fda_approved": true,
    "approval_year": "2012",
    "evidence_level": "FDA_approved",
    "line": "Add-on therapy (homozygous FH / ARH)",
    "caveat": "Hepatotoxicity risk — liver function monitoring required. REMS program. Use with maximally tolerated statins + ezetimibe.",
    "source": "FDA NDA 203858"
  },
  {
    "gene": "LDLRAP1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Inclisiran (Leqvio)",
    "action": "siRNA targeting PCSK9 mRNA in hepatocytes, reducing LDL-C by ~50%. Twice-yearly injection. Works independently of LDL receptor status — relevant for LDLRAP1 patients who have intact LDLR but impaired internalization.",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "Add-on (elevated LDL despite statins)",
    "caveat": "Efficacy in LDLRAP1-specific ARH less studied than LDLR-FH. Use if LDL remains elevated despite statin + ezetimibe.",
    "source": "FDA NDA 214012"
  },
  {
    "gene": "LDLRAP1",
    "match_functional_classes": null,
    "action_type": "drug",
    "drug_name": "Evinacumab (Evkeeza)",
    "action": "Anti-ANGPTL3 monoclonal antibody — reduces LDL independently of LDL receptor pathway entirely. Only therapy proven effective in true LDL-receptor-negative homozygous FH, also effective in LDLRAP1-ARH.",
    "fda_approved": true,
    "approval_year": "2021",
    "evidence_level": "FDA_approved",
    "line": "Add-on (homozygous FH / ARH, age ≥12)",
    "caveat": "Monthly IV infusion. Most potent LDL-lowering for receptor-pathway-independent mechanism. Reserved for severe/refractory cases.",
    "source": "FDA BLA 761181"
  },
  {
    "gene": "PKHD1",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Renal ultrasound monitoring every 6-12 months to track kidney size and cyst progression. Blood pressure monitoring.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "Guideline",
    "line": null,
    "caveat": null,
    "source": "KDIGO Guidelines"
  },
  {
    "gene": "PKHD1",
    "match_functional_classes": null,
    "action_type": "surveillance",
    "drug_name": null,
    "action": "Hepatic evaluation (liver ultrasound, liver function tests) for congenital hepatic fibrosis, a common ARPKD complication.",
    "fda_approved": null,
    "approval_year": null,
    "evidence_level": "Guideline",
    "line": null,
    "caveat": null,
    "source": "KDIGO Guidelines"
  }
]
export function lookupVariantDrugKB(gene: string, functionalClass: string | null): DrugEntry[] {
  const geneUpper = gene.toUpperCase()
  return THERAPY_KB
    .filter(e => {
      if (e.gene.toUpperCase() !== geneUpper) return false
      if (e.action_type !== 'drug') return false
      if (e.match_functional_classes === null) return true
      if (functionalClass && e.match_functional_classes.includes(functionalClass)) return true
      return false
    })
    .map(e => ({
      drug_name: e.drug_name!,
      action: e.action,
      fda_approved: e.fda_approved ?? false,
      approval_year: e.approval_year,
      evidence_level: e.evidence_level,
      line: e.line,
      caveat: e.caveat,
      source: e.source,
    }))
}

export function lookupSurveillanceKB(gene: string): SurveillanceEntry[] {
  const geneUpper = gene.toUpperCase()
  return THERAPY_KB
    .filter(e => e.gene.toUpperCase() === geneUpper && (e.action_type === 'surveillance' || e.action_type === 'surgery'))
    .map(e => ({
      recommendation: e.action,
      action_type: e.action_type,
      evidence_level: e.evidence_level,
      source: e.source,
    }))
}

export function hasGeneInVariantDrugKB(gene: string): boolean {
  const geneUpper = gene.toUpperCase()
  return THERAPY_KB.some(e => e.gene.toUpperCase() === geneUpper)
}
